[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "FOCUS"
version = "0.1.0"
description = "Fusion of Omics for Cohesive Unified Standardization"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Lorenzo Venturelli", email = "venturelli.lorenzo@proton.me"}
]
requires-python = ">=3.11"

dependencies = [
    "numpy",
    "scipy",
    "numba",
    "joblib",
    "pandas",
    "anndata",
    "mudata",
    "scanpy",
    "scikit-learn",
    "scikit-image",
    "opencv-python",
    "Pillow",
    "tifffile",
    "czifile",
    "ome-types",
    "imagecodecs",
    "readlif",
    "ramanspy",
    "tqdm",
    "psutil",
    "timm",
    "huggingface-hub",
    "flask",
    "dask",
    "shapely",
]

[project.scripts]
focus = "focus.main:main"